/**
 * Browser Action Engine (Manifest V3)
 * Step 7 of Privacy-Preserving Browser-Agent Architecture.
 *
 * Synthesizes and executes high-fidelity browser actions (click, type, scroll,
 * select, check, submit, wait, navigate) generated by the VLM reasoning layer.
 *
 * Guarantees Zero-Leakage:
 * - Semantic placeholders ([PERSON_1], [CARD_1]) and vault tokens ({{VAULT:contact.email}})
 *   are de-anonymized strictly on-device at the microsecond of DOM insertion.
 * - Raw secrets never touch the external reasoning network.
 */

import { semanticRedactor } from "./semantic_redactor.js";
import { vault } from "./vault.js";

export const ACTION_TYPES = {
  CLICK: "click",
  TYPE: "type",
  SCROLL: "scroll",
  SELECT: "select",
  CHECK: "check",
  UNCHECK: "uncheck",
  SUBMIT: "submit",
  WAIT: "wait",
  NAVIGATE: "navigate",
  FINISH: "finish"
};

export class BrowserActionEngine {
  constructor(options = {}) {
    this.showVisualIndicators = options.showVisualIndicators !== false;
    this.defaultWaitMs = options.defaultWaitMs || 1500;
  }

  /**
   * Resolves a target DOM element by selector, coordinates, or fuzzy text identifier.
   * @param {Object} action 
   * @returns {HTMLElement|null}
   */
  resolveElement(action) {
    if (!action) return null;
    if (typeof document === "undefined") return null;

    let target = null;

    // 1. CSS Selector query
    if (action.selector) {
      try {
        target = document.querySelector(action.selector);
      } catch {
        target = null;
      }
    }

    // 2. Coordinates fallback
    if (!target && action.coordinates && typeof action.coordinates.x === "number") {
      try {
        target = document.elementFromPoint(action.coordinates.x, action.coordinates.y);
      } catch {
        target = null;
      }
    }

    // 3. Fallback: Search by ID or Name
    if (!target && action.elementId) {
      target = document.getElementById(action.elementId) ||
               document.querySelector(`[name="${action.elementId}"]`);
    }

    return target;
  }

  /**
   * De-anonymizes input text locally before typing into a form field.
   * Resolves vault tokens ({{VAULT:cat.key}}) and semantic placeholders ([PERSON_1]).
   * @param {string} text 
   * @returns {string} Plaintext strictly for DOM insertion
   */
  resolveLocalValue(text) {
    if (!text || typeof text !== "string") return text || "";

    // 1. Check for vault token syntax {{VAULT:category.key}}
    if (text.startsWith("{{VAULT:") && text.endsWith("}}")) {
      if (vault.isUnlocked()) {
        const resolved = vault.resolveToken(text);
        if (resolved !== null) return resolved;
      }
    }

    // 2. De-anonymize session-scoped placeholders ([PERSON_1], [EMAIL_1], etc.)
    return semanticRedactor.deAnonymize(text);
  }

  /**
   * Dispatches visual action feedback animation on target element.
   */
  renderActionRipple(element, actionType) {
    if (!this.showVisualIndicators || !element || typeof document === "undefined") return;

    try {
      const rect = element.getBoundingClientRect();
      const indicator = document.createElement("div");
      indicator.className = "__pii_agent_action_ripple__";

      Object.assign(indicator.style, {
        position: "fixed",
        top: `${rect.top}px`,
        left: `${rect.left}px`,
        width: `${rect.width}px`,
        height: `${rect.height}px`,
        border: "2px solid #10b981",
        background: "rgba(16, 185, 129, 0.22)",
        borderRadius: "6px",
        zIndex: "2147483645",
        pointerEvents: "none",
        boxShadow: "0 0 20px rgba(16, 185, 129, 0.8)",
        transition: "all 0.6s cubic-bezier(0.16, 1, 0.3, 1)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "#ffffff",
        fontSize: "12px",
        fontWeight: "700",
        textShadow: "0 1px 3px rgba(0,0,0,0.8)"
      });

      indicator.textContent = `🤖 Action: ${actionType.toUpperCase()}`;
      document.body.appendChild(indicator);

      setTimeout(() => {
        indicator.style.opacity = "0";
        indicator.style.transform = "scale(1.06)";
        setTimeout(() => indicator.remove(), 600);
      }, 850);
    } catch {
      // Ignore animation errors
    }
  }

  /**
   * Main Dispatcher: Executes a structured action command in the browser DOM.
   * @param {Object} action Structured action from reasoning layer
   * @returns {Promise<Object>} Execution report
   */
  async execute(action) {
    const startTime = (typeof performance !== "undefined") ? performance.now() : Date.now();
    const actType = (action.type || "").toLowerCase();

    // 1. Navigation Action (does not require target element)
    if (actType === ACTION_TYPES.NAVIGATE) {
      const url = action.value || action.url;
      if (url && typeof window !== "undefined") {
        window.location.href = url;
        return { ok: true, type: ACTION_TYPES.NAVIGATE, url };
      }
      return { ok: false, error: "Missing navigation URL" };
    }

    // 2. Wait / Delay Action
    if (actType === ACTION_TYPES.WAIT) {
      const ms = parseInt(action.value, 10) || this.defaultWaitMs;
      await new Promise((res) => setTimeout(res, ms));
      return { ok: true, type: ACTION_TYPES.WAIT, durationMs: ms };
    }

    // 3. Scroll Action
    if (actType === ACTION_TYPES.SCROLL) {
      if (typeof window !== "undefined") {
        let scrollY = 400;
        let scrollX = 0;
        if (action.coordinates) {
          scrollY = action.coordinates.y || 0;
          scrollX = action.coordinates.x || 0;
        } else if (action.value === "up" || action.value === "top") {
          scrollY = -400;
        }
        window.scrollBy({ top: scrollY, left: scrollX, behavior: "smooth" });
        return { ok: true, type: ACTION_TYPES.SCROLL, delta: { x: scrollX, y: scrollY } };
      }
      return { ok: true, type: ACTION_TYPES.SCROLL };
    }

    // 4. Finish Action
    if (actType === ACTION_TYPES.FINISH) {
      return { ok: true, type: ACTION_TYPES.FINISH, explanation: action.explanation || "Task finished." };
    }

    // Resolve target element for DOM interactions
    const target = this.resolveElement(action);
    if (!target) {
      return {
        ok: false,
        type: actType,
        error: `Target element not found in DOM: ${action.selector || "coordinates"}`
      };
    }

    // Scroll into view & render ripple indicator
    try {
      target.scrollIntoView({ behavior: "smooth", block: "center" });
      this.renderActionRipple(target, actType);
    } catch {
      // Non-fatal
    }

    // 5. Click Action
    if (actType === ACTION_TYPES.CLICK) {
      target.focus();
      target.dispatchEvent(new MouseEvent("mousedown", { bubbles: true, cancelable: true, view: window }));
      target.dispatchEvent(new MouseEvent("mouseup", { bubbles: true, cancelable: true, view: window }));
      target.click();
      target.dispatchEvent(new Event("change", { bubbles: true }));
      return { ok: true, type: ACTION_TYPES.CLICK, selector: action.selector };
    }

    // 6. Type Action (Form Input Autofill with Local De-anonymization)
    if (actType === ACTION_TYPES.TYPE) {
      const plaintext = this.resolveLocalValue(action.value || "");

      target.focus();

      // Safe React 16+ input value setter
      try {
        const proto = target.tagName === "TEXTAREA" ? window.HTMLTextAreaElement.prototype : window.HTMLInputElement.prototype;
        const nativeSetter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
        if (nativeSetter) {
          nativeSetter.call(target, plaintext);
        } else {
          target.value = plaintext;
        }
      } catch {
        target.value = plaintext;
      }

      // Dispatch simulated native events
      target.dispatchEvent(new KeyboardEvent("keydown", { bubbles: true }));
      target.dispatchEvent(new Event("input", { bubbles: true }));
      target.dispatchEvent(new KeyboardEvent("keyup", { bubbles: true }));
      target.dispatchEvent(new Event("change", { bubbles: true }));

      return {
        ok: true,
        type: ACTION_TYPES.TYPE,
        selector: action.selector,
        deAnonymizedLocally: Boolean(plaintext !== action.value)
      };
    }

    // 7. Select Dropdown Action
    if (actType === ACTION_TYPES.SELECT) {
      if (target.tagName === "SELECT") {
        const val = this.resolveLocalValue(action.value || "");
        target.value = val;
        target.dispatchEvent(new Event("change", { bubbles: true }));
        return { ok: true, type: ACTION_TYPES.SELECT, value: val };
      }
      return { ok: false, error: "Target element is not a <select>" };
    }

    // 8. Check / Toggle Action
    if (actType === ACTION_TYPES.CHECK || actType === ACTION_TYPES.UNCHECK) {
      target.checked = (actType === ACTION_TYPES.CHECK);
      target.dispatchEvent(new Event("change", { bubbles: true }));
      return { ok: true, type: actType, checked: target.checked };
    }

    // 9. Submit Form Action
    if (actType === ACTION_TYPES.SUBMIT) {
      if (target.form) {
        target.form.submit();
      } else {
        target.click();
      }
      return { ok: true, type: ACTION_TYPES.SUBMIT };
    }

    return { ok: false, error: `Unsupported action type: ${action.type}` };
  }
}

// Global Singleton Instance
export const actionEngine = new BrowserActionEngine();
